skillMetadata:
  sections:
    - name: Token
      fields:
        - name: Token
          type: password
          label: Token
          value: ""

    - name: Url
      fields:
        - name: Url
          type: text
          label: Url
          value: ""

